// lib/studentIds.js
//
// Manages the pool of pre-issued Student IDs (data/student_ids.json,
// generated by scripts/generate-student-ids.js). Each entry moves through:
//
//   unassigned -> assigned -> claimed
//
//   unassigned : not yet handed to anyone
//   assigned   : an admin issued it to a specific (named) student, who
//                hasn't registered on the site with it yet
//   claimed    : a student has used it to complete registration — it's now
//                permanently tied to that student account and can't be
//                reused, even if that account is later deleted
//
// Registration on the public site (/register and /register/complete) is
// only allowed with a code that's currently "assigned" — this is what
// enforces "admin registers you first, then you can sign up".

const db = require("./db");

async function read() {
  return db.read("student_ids");
}
async function write(list) {
  return db.write("student_ids", list);
}

function normalize(code) {
  return (code || "").trim().toUpperCase();
}

function findByCode(list, code) {
  const target = normalize(code);
  return list.find((e) => e.code === target) || null;
}

function counts(list) {
  return {
    total: list.length,
    unassigned: list.filter((e) => e.status === "unassigned").length,
    assigned: list.filter((e) => e.status === "assigned").length,
    claimed: list.filter((e) => e.status === "claimed").length,
  };
}

// Hands out the next unused code to a named student. Returns the updated
// entry, or throws if the pool is exhausted (time to generate more, or
// re-run the generator script with a higher COUNT).
async function issueNext({ name, phone }) {
  const list = await read();
  const entry = list.find((e) => e.status === "unassigned");
  if (!entry) {
    throw new Error("No unassigned Student IDs left in the pool — generate more with scripts/generate-student-ids.js.");
  }
  entry.status = "assigned";
  entry.assignedTo = { name, phone: phone || null };
  entry.assignedAt = new Date().toISOString();
  await write(list);
  return entry;
}

// A code is usable for registration only while it's "assigned" (issued by
// an admin) and not yet "claimed" (already used to create an account).
async function findAssignable(code) {
  const list = await read();
  const entry = findByCode(list, code);
  if (!entry || entry.status !== "assigned") return null;
  return entry;
}

// Call this right after a student account is successfully created with
// this code, to permanently mark it used.
async function markClaimed(code, studentId) {
  const list = await read();
  const entry = findByCode(list, code);
  if (!entry) return null;
  entry.status = "claimed";
  entry.claimedBy = studentId;
  entry.claimedAt = new Date().toISOString();
  await write(list);
  return entry;
}

function search(list, query) {
  const q = (query || "").trim().toLowerCase();
  if (!q) return [];
  return list.filter(
    (e) =>
      e.code.toLowerCase().includes(q) ||
      (e.assignedTo?.name || "").toLowerCase().includes(q) ||
      (e.assignedTo?.phone || "").toLowerCase().includes(q) ||
      (e.claimedBy || "").toLowerCase().includes(q)
  );
}

// Most recently issued first — for the admin dashboard's default view.
function recentlyIssued(list, limit = 20) {
  return list
    .filter((e) => e.status !== "unassigned")
    .sort((a, b) => new Date(b.assignedAt) - new Date(a.assignedAt))
    .slice(0, limit);
}

module.exports = {
  read,
  write,
  normalize,
  findByCode,
  counts,
  issueNext,
  findAssignable,
  markClaimed,
  search,
  recentlyIssued,
};
